// genbrand renders internal/shim/brand.go from the repo-root brand.json.
// Run via `go generate ./internal/...`; `go generate ./...` also matches this
// package and corrupts its build directory with the generator's output.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
)

type brand struct {
	AppName     string `json:"appName"`
	MarkDataURI string `json:"markDataUri"`
}

const tmpl = `// Code generated by genbrand from %s; DO NOT EDIT.

package shim

//go:generate go run ../../cmd/genbrand -in ../../../brand.json -out brand.go

const AppName = %q

// MarkDataURI is the sprout mark as a square WebP, written by scripts/mascot_assets.py.
const MarkDataURI = %q
`

func main() {
	in := flag.String("in", "", "path to brand.json")
	out := flag.String("out", "", "path to write the generated Go file")
	flag.Parse()

	data, err := os.ReadFile(*in)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	var b brand
	if err := json.Unmarshal(data, &b); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}

	content := fmt.Sprintf(tmpl, *in, b.AppName, b.MarkDataURI)
	if err := os.WriteFile(*out, []byte(content), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
