// Code generated by genbrand from ../../../brand.json; DO NOT EDIT.

package shim

//go:generate go run ../../cmd/genbrand -in ../../../brand.json -out brand.go

const AppName = "kodamachi"

// MarkTileRadius and MarkGlyphPath draw the mark in a 160x160 viewBox.
const MarkTileRadius = 36.67

const MarkGlyphPath = "M49.71 125V35H64.58V86.7L91.68 60.2H109.52L84.21 84.59L110.29 125H93.44L74.02 94.76L64.58 103.87V125Z"
